# Generated by Django 5.0.3 on 2024-03-26 23:58

import django.utils.timezone
import projectsapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=projectsapi.models.upload_to)),
                ('college', models.CharField(default='', max_length=255)),
                ('investigator', models.CharField(default='', max_length=255)),
                ('region', models.CharField(default='', max_length=255)),
                ('industry', models.CharField(default='', max_length=255)),
                ('summary', models.TextField(default='')),
                ('additional_info', models.TextField(default='')),
                ('hidden', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
