# Generated by Django 5.0.3 on 2024-05-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0005_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='project',
            name='partner_organization',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(choices=[('region1', 'Region 1'), ('region2', 'Region 2'), ('region3', 'Region 3'), ('region4', 'Region 4'), ('region5', 'Region 5'), ('region6', 'Reigon 6')], default='region1', max_length=50),
        ),
    ]
