# Generated by Django 5.0.3 on 2024-05-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0006_project_keywords_project_partner_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_year',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='isWorking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='start_year',
            field=models.CharField(default='', max_length=255),
        ),
    ]
