# Generated by Django 5.0.3 on 2024-05-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0007_project_end_year_project_isworking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
