# Generated by Django 5.0.3 on 2024-05-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0008_remove_project_additional_info_project_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.TextField(default=''),
        ),
    ]
