# Generated by Django 5.0.3 on 2024-05-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0009_alter_project_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published_date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(choices=[('kircher', 'KIRCHER'), ('jheasa', 'JHEASA'), ('ausjal', 'AUSJAL'), ('ajcu-ap', 'AJCU-AP'), ('ajcu-am', 'AJCU-AM'), ('ajcu', 'AJCU')], default='kircher', max_length=50),
        ),
    ]
