# Generated by Django 5.0.3 on 2024-05-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_appuser_status_appuser_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
