# Generated by Django 5.0.3 on 2024-05-19 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('title', models.CharField(default='', max_length=255)),
                ('region', models.CharField(choices=[('region1', 'Region 1'), ('region2', 'Region 2'), ('region3', 'Region 3'), ('region4', 'Region 4'), ('region5', 'Region 5'), ('region6', 'Reigon 6')], default='region1', max_length=50)),
                ('hidden', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
