# Generated by Django 5.0.3 on 2024-04-29 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='', max_length=255)),
                ('topics', models.CharField(default='', max_length=255)),
                ('hidden', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
