# Generated by Django 5.0.3 on 2024-04-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centersapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='center',
            field=models.CharField(default='', max_length=255),
        ),
    ]
