# Generated by Django 5.0.3 on 2024-04-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centersapi', '0002_center_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='title',
        ),
    ]
