# Generated by Django 5.0.3 on 2024-04-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centersapi', '0003_remove_center_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
