# Generated by Django 5.0.3 on 2024-05-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centersapi', '0004_center_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='description',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='director',
            new_name='location',
        ),
        migrations.AddField(
            model_name='center',
            name='program_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
