# Generated by Django 5.0.3 on 2024-04-04 18:08

import django.utils.timezone
import docsapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('cover_url', models.ImageField(blank=True, null=True, upload_to=docsapi.models.upload_to)),
                ('document', models.FileField(upload_to=docsapi.models.upload_to_file)),
                ('hidden', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
