# Generated by Django 5.0.3 on 2024-04-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='cover_url',
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.CharField(default='', max_length=255),
        ),
    ]
