# Generated by Django 5.0.3 on 2024-04-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsapi', '0002_remove_document_cover_url_document_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
    ]
