# Generated by Django 5.0.3 on 2024-04-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
